//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "DropViewDelegate.h"
#import "NSApplicationDelegate.h"
#import "NSWindowDelegate.h"

@class BadgeNumberButton, HistoryWindowController, MTableView, NSButton, NSMutableArray, NSString, NSTextField, NSView, ProductController, ProgressWindowController;

__attribute__((visibility("hidden")))
@interface AppController : NSWindowController <NSApplicationDelegate, NSWindowDelegate, DropViewDelegate>
{
    NSView *titleBarView;
    NSView *bottomBarView;
    ProgressWindowController *progressWindowController;
    HistoryWindowController *historyWindowController;
    ProductController *productController;
    MTableView *convertTableView;
    NSMutableArray *convertItems;
    id <AddWindowControllerProtocol> addWindowController;
    NSTextField *appTitleField;
    NSTextField *audioInfoField;
    NSButton *buyButton;
    NSButton *unregisterButton;
    NSButton *guideAddButton;
    NSButton *convertButton;
    BadgeNumberButton *historyButton;
}

+ (id)fontForSize:(double)arg1;
+ (void)initialize;
- (void)keyDown:(id)arg1;
- (void)history:(id)arg1;
- (void)convert:(id)arg1;
- (void)remove:(id)arg1;
- (void)add:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (BOOL)tableView:(id)arg1 shouldEditTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)updateMediaInfo;
- (void)URIDidReceived:(id)arg1 forURL:(id)arg2;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)userDidFinishRegister:(id)arg1;
- (void)injectDidFailure:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(id)arg1;
- (struct CGRect)window:(id)arg1 willPositionSheet:(id)arg2 usingRect:(struct CGRect)arg3;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)showGuideView:(BOOL)arg1;
- (void)awakeFromNib;
- (id)productController;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

