//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface BadgeNumberView : NSView
{
    struct CGSize textSize;
    NSDictionary *textAttr;
    NSString *badgeString;
}

- (void)drawRect:(struct CGRect)arg1;
- (void)setBadgeTitle:(id)arg1;
- (struct CGSize)calcFrameSize;
- (void)dealloc;
- (id)init;
- (BOOL)acceptsFirstResponder;
- (BOOL)isOpaque;

@end

