//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class NSMutableDictionary, NSOutlineView, NSString;

__attribute__((visibility("hidden")))
@interface HistoryWindowController : NSWindowController <NSWindowDelegate>
{
    NSOutlineView *historyOutlineView;
    NSMutableDictionary *records;
    NSMutableDictionary *historyLibrary;
}

- (void)alertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)keyDown:(id)arg1;
- (void)removeRecordFromList:(id)arg1;
- (void)btnDeleteFromList:(id)arg1;
- (void)btnShowInFinder:(id)arg1;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (void)windowWillClose:(id)arg1;
- (void)runModal;
- (BOOL)addConvertedItem:(id)arg1 destinationPath:(id)arg2;
- (id)convertedTrackURLs;
- (void)removeItemsFromFile:(id)arg1;
- (BOOL)loadHistoryRecordFile;
- (id)historyRecordFilePath;
- (id)dateStringFromDateTime:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (id)init;
- (void)showGuideView:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

