//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "INWindowBackgroundView.h"

@interface INWindowBackgroundView (CoreUIRendering)
+ (void)loadConstant:(const id *)arg1 named:(id)arg2 fromBundle:(struct __CFBundle *)arg3;
+ (void)load;
- (void)drawCUIWindowBackgroundLayersInRect:(struct CGRect)arg1 forEdge:(unsigned int)arg2 showsSeparator:(BOOL)arg3 clippingPath:(struct CGPath *)arg4;
@end

