//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

__attribute__((visibility("hidden")))
@interface INWindowBackgroundView : NSView
{
}

+ (id)windowPatternOverlayColor;
- (struct CGRect)baselineSeparatorFrameForRect:(struct CGRect)arg1 edge:(unsigned long long)arg2;
- (void)drawWindowBackgroundLayersInRect:(struct CGRect)arg1 forEdge:(unsigned long long)arg2 showsSeparator:(BOOL)arg3 clippingPath:(struct CGPath *)arg4;
- (void)drawBackgroundGradientInRect:(struct CGRect)arg1 forEdge:(unsigned long long)arg2;
- (void)drawSeparatorInRect:(struct CGRect)arg1 forEdge:(unsigned long long)arg2;
- (void)drawWindowPatternOverlayColorInRect:(struct CGRect)arg1 forEdge:(unsigned long long)arg2;

@end

