//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BackgroundView.h"

@class NSView;

__attribute__((visibility("hidden")))
@interface MGuideView : BackgroundView
{
    NSView *_guideView;
    BOOL _isShowGuideView;
}

@property NSView *guideView; // @synthesize guideView=_guideView;
- (void)drawRect:(struct CGRect)arg1;
@property(getter=isShowGuideView, setter=setIsShowGuideView:) BOOL isShowGuideView; // @synthesize isShowGuideView=_isShowGuideView;
- (void)updateSubGuideView;

@end

