//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@class NSColor;

__attribute__((visibility("hidden")))
@interface MTableView : NSTableView
{
    NSColor *_selectionColor;
}

@property(retain) NSColor *selectionColor; // @synthesize selectionColor=_selectionColor;
- (void)highlightSelectionInClipRect:(struct CGRect)arg1;
- (id)_highlightColorForCell:(id)arg1;

@end

