//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSDate, NSImageView, NSMutableArray, NSPopUpButton, NSProgressIndicator, NSTextField;

__attribute__((visibility("hidden")))
@interface ProgressWindowController : NSWindowController
{
    BOOL isAbort;
    int totalCount;
    int currentIndex;
    double totalDuration;
    NSDate *beginConvertTime;
    NSMutableArray *convertTracks;
    NSTextField *fileNameField;
    NSTextField *indexInfoField;
    NSTextField *remainTimeInfoField;
    NSProgressIndicator *convertingProgressIndicator;
    NSProgressIndicator *singleProgressIndicator;
    NSProgressIndicator *totalProgressIndicator;
    NSPopUpButton *finishActionButton;
    NSImageView *trackArtworkImageView;
}

- (void)updateConverter:(id)arg1 convertedDuration:(double)arg2 totalConvertedDuration:(double)arg3;
- (void)doFinishAction;
- (void)abort:(id)arg1;
- (void)finish:(BOOL)arg1;
- (void)convertWithTracks:(id)arg1 completeHandler:(CDUnknownBlockType)arg2;
- (id)metadataFromTrack:(id)arg1;
- (id)profileFromPreferences;
- (BOOL)ensureEnoughDiskSpaceWithDuration:(double)arg1 profile:(id)arg2;
- (id)windowNibName;

@end

