//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

#import "NSValidatedUserInterfaceItem.h"

__attribute__((visibility("hidden")))
@interface ValidatedButton : NSButton <NSValidatedUserInterfaceItem>
{
}

@property(readonly) SEL action;
@property(readonly) long long tag;
- (void)dealloc;
- (void)windowDidUpdate:(id)arg1;
- (void)viewDidMoveToWindow;
- (id)initWithCoder:(id)arg1;

@end

