//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@class INMovableByBackgroundContainerView, INWindowButton, NSColor, NSFont, NSGradient, NSShadow, NSTextField, NSView;

__attribute__((visibility("hidden")))
@interface INAppStoreWindow : NSWindow
{
    double _titleBarHeight;
    NSView *_titleBarView;
    double _bottomBarHeight;
    NSView *_bottomBarView;
    BOOL _centerFullScreenButton;
    BOOL _centerTrafficLightButtons;
    BOOL _verticalTrafficLightButtons;
    BOOL _verticallyCenterTitle;
    BOOL _hideTitleBarInFullScreen;
    BOOL _showsBaselineSeparator;
    BOOL _showsBottomBarSeparator;
    double _trafficLightButtonsLeftMargin;
    double _trafficLightButtonsTopMargin;
    double _fullScreenButtonRightMargin;
    double _fullScreenButtonTopMargin;
    double _trafficLightSeparation;
    double _mouseDragDetectionThreshold;
    BOOL _showsTitle;
    BOOL _showsTitleInFullscreen;
    BOOL _showsDocumentProxyIcon;
    INWindowButton *_closeButton;
    INWindowButton *_minimizeButton;
    INWindowButton *_zoomButton;
    INWindowButton *_fullScreenButton;
    NSTextField *_titleDivider;
    NSFont *_titleFont;
    NSGradient *_titleBarGradient;
    NSGradient *_bottomBarGradient;
    NSColor *_baselineSeparatorColor;
    NSColor *_titleTextColor;
    NSShadow *_titleTextShadow;
    NSGradient *_inactiveTitleBarGradient;
    NSGradient *_inactiveBottomBarGradient;
    NSColor *_inactiveBaselineSeparatorColor;
    NSColor *_inactiveTitleTextColor;
    NSShadow *_inactiveTitleTextShadow;
    CDUnknownBlockType _titleBarDrawingBlock;
    CDUnknownBlockType _bottomBarDrawingBlock;
    BOOL _drawsTitlePatternOverlay;
    double _cachedTitleBarHeight;
    BOOL _setFullScreenButtonRightMargin;
    BOOL _preventWindowFrameChange;
    INMovableByBackgroundContainerView *_titleBarContainer;
    INMovableByBackgroundContainerView *_bottomBarContainer;
}

+ (id)defaultTitleTextColor:(BOOL)arg1;
+ (id)defaultBaselineSeparatorColor:(BOOL)arg1;
+ (id)defaultBottomBarGradient:(BOOL)arg1;
+ (id)defaultTitleBarGradient:(BOOL)arg1;
@property(retain, nonatomic) NSColor *inactiveBaselineSeparatorColor; // @synthesize inactiveBaselineSeparatorColor=_inactiveBaselineSeparatorColor;
@property(retain, nonatomic) NSGradient *inactiveBottomBarGradient; // @synthesize inactiveBottomBarGradient=_inactiveBottomBarGradient;
@property(retain, nonatomic) NSGradient *inactiveTitleBarGradient; // @synthesize inactiveTitleBarGradient=_inactiveTitleBarGradient;
@property(nonatomic) double trafficLightButtonsLeftMargin; // @synthesize trafficLightButtonsLeftMargin=_trafficLightButtonsLeftMargin;
@property(nonatomic) double fullScreenButtonRightMargin; // @synthesize fullScreenButtonRightMargin=_fullScreenButtonRightMargin;
@property(nonatomic) BOOL showsBottomBarSeparator; // @synthesize showsBottomBarSeparator=_showsBottomBarSeparator;
@property(nonatomic) BOOL showsBaselineSeparator; // @synthesize showsBaselineSeparator=_showsBaselineSeparator;
@property(nonatomic) BOOL hideTitleBarInFullScreen; // @synthesize hideTitleBarInFullScreen=_hideTitleBarInFullScreen;
@property(nonatomic) BOOL verticalTrafficLightButtons; // @synthesize verticalTrafficLightButtons=_verticalTrafficLightButtons;
@property(nonatomic) BOOL centerTrafficLightButtons; // @synthesize centerTrafficLightButtons=_centerTrafficLightButtons;
@property(nonatomic) BOOL centerFullScreenButton; // @synthesize centerFullScreenButton=_centerFullScreenButton;
@property(nonatomic) double bottomBarHeight; // @synthesize bottomBarHeight=_bottomBarHeight;
@property(retain, nonatomic) NSView *bottomBarView; // @synthesize bottomBarView=_bottomBarView;
@property(nonatomic) double titleBarHeight; // @synthesize titleBarHeight=_titleBarHeight;
@property(retain, nonatomic) NSView *titleBarView; // @synthesize titleBarView=_titleBarView;
@property(nonatomic) BOOL drawsTitlePatternOverlay; // @synthesize drawsTitlePatternOverlay=_drawsTitlePatternOverlay;
@property(copy, nonatomic) CDUnknownBlockType bottomBarDrawingBlock; // @synthesize bottomBarDrawingBlock=_bottomBarDrawingBlock;
@property(copy, nonatomic) CDUnknownBlockType titleBarDrawingBlock; // @synthesize titleBarDrawingBlock=_titleBarDrawingBlock;
@property(retain, nonatomic) NSShadow *inactiveTitleTextShadow; // @synthesize inactiveTitleTextShadow=_inactiveTitleTextShadow;
@property(retain, nonatomic) NSColor *inactiveTitleTextColor; // @synthesize inactiveTitleTextColor=_inactiveTitleTextColor;
@property(retain, nonatomic) NSShadow *titleTextShadow; // @synthesize titleTextShadow=_titleTextShadow;
@property(retain, nonatomic) NSColor *titleTextColor; // @synthesize titleTextColor=_titleTextColor;
@property(retain, nonatomic) NSColor *baselineSeparatorColor; // @synthesize baselineSeparatorColor=_baselineSeparatorColor;
@property(retain, nonatomic) NSGradient *bottomBarGradient; // @synthesize bottomBarGradient=_bottomBarGradient;
@property(retain, nonatomic) NSGradient *titleBarGradient; // @synthesize titleBarGradient=_titleBarGradient;
@property(retain, nonatomic) NSFont *titleFont; // @synthesize titleFont=_titleFont;
@property(retain, nonatomic) INWindowButton *fullScreenButton; // @synthesize fullScreenButton=_fullScreenButton;
@property(retain, nonatomic) INWindowButton *zoomButton; // @synthesize zoomButton=_zoomButton;
@property(retain, nonatomic) INWindowButton *minimizeButton; // @synthesize minimizeButton=_minimizeButton;
@property(retain, nonatomic) INWindowButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) BOOL showsDocumentProxyIcon; // @synthesize showsDocumentProxyIcon=_showsDocumentProxyIcon;
@property(nonatomic) BOOL showsTitleInFullscreen; // @synthesize showsTitleInFullscreen=_showsTitleInFullscreen;
@property(nonatomic) BOOL showsTitle; // @synthesize showsTitle=_showsTitle;
@property(nonatomic) double trafficLightSeparation; // @synthesize trafficLightSeparation=_trafficLightSeparation;
@property(nonatomic) double fullScreenButtonTopMargin; // @synthesize fullScreenButtonTopMargin=_fullScreenButtonTopMargin;
@property(nonatomic) double trafficLightButtonsTopMargin; // @synthesize trafficLightButtonsTopMargin=_trafficLightButtonsTopMargin;
@property(nonatomic) BOOL verticallyCenterTitle; // @synthesize verticallyCenterTitle=_verticallyCenterTitle;
- (void)_updateBottomBarView;
- (void)_updateTitlebarView;
- (void)_displayWindowAndTitlebar;
- (double)_defaultTrafficLightSeparation;
- (double)_defaultTrafficLightLeftMargin;
- (double)_minimumTitlebarHeight;
- (void)_repositionContentView;
- (struct CGRect)_contentViewFrame;
- (void)_recalculateFrameForBottomBarContainer;
- (void)_recalculateFrameForTitleBarContainer;
- (void)_setupTrafficLightsTrackingArea;
- (void)_setTitleBarViewHidden:(BOOL)arg1;
- (void)_createBottomBarView;
- (void)_createTitlebarView;
- (id)themeFrameView;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)windowWillExitFullScreen:(id)arg1;
- (void)windowWillEnterFullScreen:(id)arg1;
- (void)undoManagerDidCloseUndoGroupNotification:(id)arg1;
- (void)_layoutTrafficLightsAndContent;
- (id)_fullScreenButtonToLayout;
- (id)_zoomButtonToLayout;
- (id)_minimizeButtonToLayout;
- (id)_closeButtonToLayout;
- (id)_windowButtonToLayout:(unsigned long long)arg1 orUserProvided:(id)arg2;
- (void)_doInitialWindowSetup;
- (double)toolbarHeight;
- (void)setFrame:(struct CGRect)arg1 display:(BOOL)arg2 animate:(BOOL)arg3;
- (void)setFrame:(struct CGRect)arg1 display:(BOOL)arg2;
- (void)setStyleMask:(unsigned long long)arg1;
@property(readonly, nonatomic) NSTextField *titleDivider; // @synthesize titleDivider=_titleDivider;
@property(nonatomic) double mouseDragDetectionThreshold; // @synthesize mouseDragDetectionThreshold=_mouseDragDetectionThreshold;
- (void)setTitleBarHeight:(double)arg1 adjustWindowFrame:(BOOL)arg2;
- (void)toggleToolbarShown:(id)arg1;
- (void)setToolbar:(id)arg1;
- (void)setMinSize:(struct CGSize)arg1;
- (void)setMaxSize:(struct CGSize)arg1;
- (void)setTitle:(id)arg1;
- (void)setContentView:(id)arg1;
- (void)resignMainWindow;
- (void)becomeMainWindow;
- (void)resignKeyWindow;
- (void)becomeKeyWindow;
- (void)dealloc;
- (void)setRepresentedURL:(id)arg1;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4 screen:(id)arg5;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4;

@end

