//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface InjectorHelper : NSObject
{
}

+ (id)fixUpdaterPath:(id)arg1;
+ (BOOL)doAuthorizedOperations:(CDUnknownBlockType)arg1;
+ (int)injectorModeForBundle:(id)arg1;
+ (id)ITunesHelperPath;
+ (_Bool)isSIPEnabled;
+ (BOOL)isOnlyRecordMode;
+ (id)applicationVersions:(id)arg1;
+ (void)initialize;

@end

