//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSRunningApplication, NSString;

__attribute__((visibility("hidden")))
@interface MusicApplication : NSObject
{
    NSString *pluginPath;
    NSRunningApplication *runningApp;
    unsigned int buildinOutputDevice;
    unsigned int activeOutputDevice;
    int mode;
    NSString *_appPath;
    NSString *_appVersion;
}

+ (id)runningAppWithPath:(id)arg1;
@property(readonly) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain) NSString *appPath; // @synthesize appPath=_appPath;
- (void)getActiveAudioDevice:(unsigned int *)arg1 buildinAudioDevice:(unsigned int *)arg2;
- (BOOL)setOutputDevice:(unsigned int)arg1;
- (BOOL)setOutputDeviceToBuildin;
- (void)hideApplicationWindow;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)close;
- (BOOL)open;
- (BOOL)isRunning;
- (void)dealloc;
- (id)initWithPluginPath:(id)arg1;

@end

