//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "Converter.h"

@class MusicApplication, NSImage, NSString;

__attribute__((visibility("hidden")))
@interface MusicConverter : NSObject <Converter>
{
    id <ConvertCommunicationProtocol> converterCore;
    MusicApplication *musicApp;
    NSString *musicAppIdentifer;
    NSString *pluginPath;
    long long timeoutValue;
    NSImage *_currentTrackArtwork;
}

+ (id)converterLogPath;
+ (id)sharedMusicConverter;
@property(retain) NSImage *currentTrackArtwork; // @synthesize currentTrackArtwork=_currentTrackArtwork;
- (void)disconnectToConvertCore;
- (BOOL)connectToConvertCore;
- (BOOL)convertFile:(id)arg1 output:(id)arg2 metadata:(id)arg3 convertSpeed:(int)arg4 withProfile:(id)arg5 progressHandler:(CDUnknownBlockType)arg6;
- (void)closeMusicApp;
- (BOOL)openMusicApp;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

