//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class NSButton, NSPopUpButton, NSString;

__attribute__((visibility("hidden")))
@interface PreferenceWindowController : NSWindowController <NSWindowDelegate>
{
    NSPopUpButton *speedPopupButton;
    NSButton *keepChapterButton;
}

+ (void)initialize;
- (void)windowWillClose:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)changeKeepChapterOption:(id)arg1;
- (void)changeOutputFormat:(id)arg1;
- (void)changeOutputFolder:(id)arg1;
- (void)openLogFolder:(id)arg1;
- (void)awakeFromNib;
- (id)windowNibName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

